(test
 (name test_dynamodb_value)
 (modules test_dynamodb_value)
 (libraries dynamodb_eio aws-eio alcotest yojson))

(test
 (name test_dynamodb_error)
 (modules test_dynamodb_error)
 (libraries dynamodb_eio aws-eio alcotest))

(test
 (name test_dynamodb_client)
 (modules test_dynamodb_client)
 (libraries dynamodb_eio aws-eio alcotest yojson eio_main))

(test
 (name test_dynamodb_table)
 (modules test_dynamodb_table)
 (libraries dynamodb_eio aws-eio alcotest))

(test
 (name test_dynamodb_live)
 (modules test_dynamodb_live)
 (libraries dynamodb_eio aws-eio alcotest eio_main))
